zad1:
	gcc -Wall -o zad1 zad1.c
	./zad1
	rm -f zad1

zad2:
	gcc zad2.c `pkg-config --cflags --libs gsl` -o zad2
	./zad2
	rm -f zad2

zad3:
	gcc -Wall -o zad3 zad3.c
	./zad3
	rm -f zad3

zad4:
	gcc zad4.c `pkg-config --cflags --libs gsl` -o zad4
	./zad4
	rm -f zad4

zad5:
	gcc -Wall -o zad5 zad5.c
	./zad5
	rm -f zad5
