mainmain:
	gcc -Wall -g main.c `pkg-config --cflags --libs gsl` -o main

clean:
	rm -f main

testt:
	./main 1000
	./main 1100
	./main 1200
	./main 1300
	./main 1400
	./main 1500
	./main 1600
	./main 1700
	./main 1800
	./main 1900
	./main 2000
